
export enum BOOKING_STATUS {
  NOT_CONFIRMED = 'NOT CONFIRMED',
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED'
}

export enum BOOKING_PAYMENT_METHOD {
  STRIPE = 'STRIPE',
  BANK = 'BANK'
}