export enum USER_ROLES {
  SUPER_ADMIN = 'SUPER ADMIN',
  ADMIN = 'ADMIN',
  USER = 'USER',
  DRIVER = 'DRIVER',
  TEAM_MEMBER = 'TEAM MEMBER',
  CLIENT = 'CLIENT',
}
export enum TEAM_ROLES {
  AUTHORITY = 'AUTHORITY',
  MEMBER = 'MEMBER',
}
