export enum VEHICLE_TYPES {
  LARGE_PREMIUM = 'LARGE_PREMIUM',
  LARGE_STATION_WAGON = 'LARGE_STATION_WAGON',
  MEDIUM_LOW_EMISSION = 'MEDIUM_LOW_EMISSION',
  SMALL_ECONOMY = 'SMALL_ECONOMY',
  SMALL_MINI = 'SMALL_MINI',
}

export enum TRANSMISSION_TYPES {
  AUTOMATIC = 'AUTOMATIC',
  MANUAL = 'MANUAL',
}

export enum FUEL_TYPES {
  PETROL = 'PETROL',
  DIESEL = 'DIESEL',
  ELECTRIC = 'ELECTRIC',
  HYBRID = 'HYBRID',
}

