export enum VEHICLE_TYPES {
  LARGE_PREMIUM = 'LARGE PREMIUM',
  LARGE_STATION_WAGON = 'LARGE STATION WAGON',
  MEDIUM_LOW_EMISSION = 'MEDIUM LOW EMISSION',
  SMALL_ECONOMY = 'SMALL ECONOMY',
  SMALL_MINI = 'SMALL MINI',
}

export enum TRANSMISSION_TYPES {
  AUTOMATIC = 'AUTOMATIC',
  MANUAL = 'MANUAL',
}

export enum FUEL_TYPES {
  PETROL = 'PETROL',
  DIESEL = 'DIESEL',
  ELECTRIC = 'ELECTRIC',
  HYBRID = 'HYBRID',
}

export enum VEHICLE_STATUS {
  AVAILABLE = 'AVAILABLE',
  RENTED = 'RENTED',
  MAINTENANCE = 'MAINTENANCE',
  SOLD = 'SOLD',
}

// Use VEHICLE_TYPES as keys for the pricing chart
export const PRICING_CHART: Record<VEHICLE_TYPES, number> = {
  [VEHICLE_TYPES.LARGE_PREMIUM]: 1.5,
  [VEHICLE_TYPES.LARGE_STATION_WAGON]: 1.2,
  [VEHICLE_TYPES.MEDIUM_LOW_EMISSION]: 1.0, // standard base rate
  [VEHICLE_TYPES.SMALL_ECONOMY]: 0.8,
  [VEHICLE_TYPES.SMALL_MINI]: 0.7,
};