export enum VEHICLE_TYPES {
  LARGE_PREMIUM = 'LARGE PREMIUM',
  LARGE_STATION_WAGON = 'LARGE_STATION WAGON',
  MEDIUM_LOW_EMISSION = 'MEDIUM LOW EMISSION',
  SMALL_ECONOMY = 'SMALL ECONOMY',
  SMALL_MINI = 'SMALL MINI',
}

export enum TRANSMISSION_TYPES {
  AUTOMATIC = 'AUTOMATIC',
  MANUAL = 'MANUAL',
}

export enum FUEL_TYPES {
  PETROL = 'PETROL',
  DIESEL = 'DIESEL',
  ELECTRIC = 'ELECTRIC',
  HYBRID = 'HYBRID',
}

export enum VEHICLE_STATUS {
  AVAILABLE = 'AVAILABLE',
  RENTED = 'RENTED',
  MAINTENANCE = 'MAINTENANCE',
  SOLD = 'SOLD',
}
