 
name: OOTMS_Backend CI/CD

on:
  push:
    branches: [ "main" ] 

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [ 22.x]
      
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present  
    - name: Change Directory
      run: cd /home/mentor/actions-runner-ootms/_work/ootms_server/ootms_server
    - run: pm2 restart 2